# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extropy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='edate',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ename',
            field=models.CharField(max_length=250, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='idno',
            field=models.CharField(max_length=400, verbose_name='Id No.'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
