# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extropy', '0002_auto_20171119_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
