# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extropy', '0008_auto_20171206_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='event',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.AddField(
            model_name='register',
            name='application',
            field=models.TextField(default='blank', max_length=5000, verbose_name='Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='objective',
            field=models.TextField(default='blank', max_length=5000, verbose_name='Objective'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='abstract',
            field=models.TextField(max_length=5000, verbose_name='Abstract'),
        ),
    ]
