# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extropy', '0009_auto_20171206_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='application',
        ),
        migrations.AddField(
            model_name='register',
            name='title',
            field=models.CharField(default='blank', max_length=400),
            preserve_default=False,
        ),
    ]
